### ISSUE TITLE
CLI pasting via curl

### ISSUE THREAD

**Issue by kozross** [tomsmeding/pastebin-haskell#12]
For some services (such as `ix.io`), you can paste from the command line using curl:

```
cat foo | curl -F 'f:1=<-' ix.io
```

Is something similar possible with this? If not, could we make it be possible?

**Comment by tomsmeding** [comment]
This is in fact possible; it has been requested by someone on IRC before, and apparently curl has some syntax that makes it work:

    cat foo | curl -d 'name1=a.txt' --data-urlencode 'code1@/dev/stdin' https://paste.tomsmeding.com/paste

Note that this does not send the data in a form, because the server doesn't understand `multipart/form-data`-style HTTP requests. Instead it sends it as plain POST parameters.

You can also send multiple files this way: just add name2 & code2, etc. parameters. (Then you might not want to use /dev/stdin ;).) An empty name means "no filename given".

Hm, maybe this should be documented somewhere.
